config/routes.rb
Directory::Application.routes.draw do

  get "home/index"

  resources :events

  resources :groups

  resources :contacts

  resources :roles do
    put 'assign', :on => :member
    put 'remove', :on => :member
  end 

  devise_for :users, do
    get "sign_in", :to => "devise/sessions#new" 
  end
 
  resources :users

  

  root :to => "home#index" 

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :contact
  has_and_belongs_to_many :roles
  has_many :relationships
  has_many :contacts, :through => :relationships
  has_and_belongs_to_many :groups

  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :role_ids, :admin, :name, :contact_id

  def role?(role)
    return !!self.roles.find_by_name(role)
  end

  def all_roles
    if self.admin?
      return "Admin, " + self.roles.collect{|r| r.name}.join(", ")
    else
      return self.roles.collect{|r| r.name}.join(", ")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, :only => [:index, :new, :edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]

  # GET /users
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users}
    end
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user}
    end
  end

  # GET /users/new
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user}
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @contacts = Contact.all
  end
  
  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])
    params[:user][:role_ids] ||= []
    # TODO: if password is blank, then use the origional password 
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # Make the current user object available to views
  def get_user
    @current_user = current_user
  end

  # Get roles accessible by the current user
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability, :read)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'user_profile' %>

  <% if can? :read, Role %>
    <%= f.label :role %>
    <div class="field">
      <%= f.check_box :admin %> Admin
    </div>
    <% for r in Role.all %>
      <div class="field">
      <%= check_box_tag "user[role_ids][]", r.id, @user.roles.include?(r) %>
      <%= r.name %>
      </div>
    <% end %> 
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email%>
  </div>
  
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
 
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :profile %>
    <%= f.select(:contact_id, @contacts.collect {|c| [c.full_name, c.id]}, options ={:prompt => "Select a profile from contact"} )%>
  </div>
 
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>
  

app/views/users/_user_profile.html.erb
<!-- pick dropdown exisiting contacts or new contact -->

app/views/users/_users_table.html.erb
<h2>Users</h2>
<%= link_to 'Add User', new_user_path %>
<table class="dataTable">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Roles</th>
    <th>Actions</th>
  </tr>

<% @users.each do |u| %>
  <tr>
    <td>
<% if can? :read, User %>
  <%= u.name %>
<% end %>
    </td>
    <td><%= u.email %></td>
    <td><%= u.all_roles %></td>
    <td>
<% if can? :edit, User %>
  <%= link_to "Edit", edit_user_path(u.id) %>
<% end %>
      </td>
  </tr>
<% end %>
</table>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'New profile', new_contact_path %>

app/views/users/index.html.erb
<%= render 'users_table' %>

app/views/users/new.html.erb
<h1>Add User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>