config/routes.rb
Directory::Application.routes.draw do

  get "home/index"

  resources :events

  resources :groups

  resources :contacts

  resources :roles do
    put 'assign', :on => :member
    put 'remove', :on => :member
  end 

  devise_for :users, do
    get "sign_in", :to => "devise/sessions#new" 
  end
 
  resources :users

  

  root :to => "home#index" 

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
  # GET /admin/roles
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  # GET /admin/roles/1
  def show
    @role = Role.find(params[:id])
    @users = @role.users

    @existing_users = User.where(["id not in (?)", @users.map(&:id)])
    @user = User.new

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /admin/roles/new
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /admin/roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /admin/roles
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /admin/roles/1
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /admin/roles/1
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  # GET /roles/1
  def show
    @role = Role.find(params[:id])
    @users = @role.users

    @existing_users = User.where(["id not in (?)", @users.map(&:id)])
    @user = User.new

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /roles/new
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end

  def assign
    # assign users to role
    @role = Role.find(params[:id])
    if params[:commit] == "Add"
      @role.user_ids += params[:assign_user_ids]
    elsif params[:commit] == "Remove"
      @role.user_ids -= params[:remove_user_ids].map(&:to_i)
    end
    
    redirect_to :action => :show
  end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h2>Roles</h2>

<%= link_to 'New Role', new_role_path %>

<table class="dataTable">
  <tr>
    <th>Role</th>
    <th># of Users</th>
    <th>Action</th>
  </tr>
  <tr>
    <td>Admin</td>
    <td></td>
    <td>Add/Remove Users</td> 
  </tr>
<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= role.user_ids.size %></td>
    <td><%= link_to 'Add/Remove Users', role %> | Delete Role</td>
  </tr>
<% end %> 

</table>

<br />

app/views/roles/new.html.erb
<h2>New role</h2>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Role: <%= @role.name %></h2>
<%= link_to 'Edit', edit_role_path(@role) %> <br />

<h3>Remove users from <%= @role.name %></h3> 
<b><%= @role.user_ids.size %></b> users are <%= @role.name %> <br />
<%= form_tag assign_role_path, :method => :put do %>
  <% for u in @users %>
    <div class="field">
      <%= check_box_tag "remove_user_ids[]", u.id %>
      <%= u.email %>
    </div>
  <% end %>
  <div class="button">
  <%= submit_tag "Remove" %>
  </div>

<h3>Assign users to <%= @role.name %></h3> 
  <% for eu in @existing_users %>
    <div class="field">
      <%= check_box_tag "assign_user_ids[]", eu.id %>
      <%= eu.email %>
    </div>
  <% end %>
  <div class="button">
  <%= submit_tag "Add" %>
  </div>
<% end %>


<%= link_to 'Back', roles_path %>