config/routes.rb
Directory::Application.routes.draw do

  get "home/index"

  resources :events

  resources :groups

  resources :contacts

  resources :roles do
    put 'assign', :on => :member
    put 'remove', :on => :member
  end 

  devise_for :users, do
    get "sign_in", :to => "devise/sessions#new" 
  end
 
  resources :users

  

  root :to => "home#index" 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directory</title>
  <%= stylesheet_link_tag "application", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application"%>
  <%= csrf_meta_tag %>
</head>
<body>


<div id="container">
  <div id="header">
    <h1>
     Directory 
    </h1>
    <div class="user_nav">
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you? 
        <%= link_to "Sign out", destroy_user_session_path %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </div> 
  </div>
<% if user_signed_in? %>
  <div id="navigation">
    <ul>
      <li><%= link_to "Home", users_path %></a></li>
      <li><%= link_to "Events", events_path %></a></li>
      <li><%= link_to "Contacts", contacts_path %></a></li>
    </ul>
  </div>
<% end %>
  <div id="content-container">
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
    <div id="aside">
      <% if can? :manage, User %>
        <%= link_to "Users", users_path %> <br />
        <%= link_to "Roles", roles_path %> <br />
        <%= link_to "Groups", groups_path %> <br />
      <% end %>
      <%= yield :sidebar %>
    </div>
    <% end %>

    <div id="content">
<%= yield %>
    </div>
    <div id="footer">
      Copyright © Site name, 2010
    </div>
  </div>
</div>

</body>
</html>